export const SAMPLE_PRODUCT = {
  id: 'prod-1',
  sku: 'WHEY-1',
  name: 'Whey Protein Gold',
  description: 'Proteína de suero.',
  price: 899,
  stock: 10,
  is_active: true,
  category_id: 'cat-1',
  category: 'Proteínas',
  category_slug: 'proteinas',
  image_url: null,
};

export const RAW_PRODUCT_ROW = {
  id: 'prod-1',
  sku: 'WHEY-1',
  name: 'Whey Protein Gold',
  description: 'Proteína de suero.',
  price: 899,
  stock: 10,
  is_active: true,
  category_id: 'cat-1',
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
  product_categories: { id: 'cat-1', name: 'Proteínas', slug: 'proteinas' },
  product_images: [],
};

export const CHATBOT_CATALOG = [
  {
    id: '1',
    name: 'Whey Protein 2lb',
    sku: 'WHEY-2',
    price: 45,
    stock: 10,
    category: 'Proteínas',
    category_slug: 'proteinas',
    is_active: true,
  },
  {
    id: '2',
    name: 'Creatina Monohidrato',
    price: 25,
    stock: 5,
    category: 'Proteínas',
    category_slug: 'proteinas',
    is_active: true,
  },
  {
    id: '3',
    name: 'Multivitamínico Daily',
    price: 18,
    stock: 8,
    category: 'Vitaminas',
    category_slug: 'vitaminas',
    is_active: true,
  },
  {
    id: '4',
    name: 'CLA Quemador',
    price: 30,
    stock: 2,
    category: 'Control de peso',
    category_slug: 'control-peso',
    is_active: true,
  },
];

export const DASHBOARD_STATS_MOCK = {
  users: 12,
  customers: 8,
  sellers: 2,
  products: 25,
  activeProducts: 20,
  lowStock: 3,
  orders: 15,
  pendingOrders: 4,
  sales: 10,
  payments: 10,
  conversations: 6,
  pendingHandoffs: 1,
  tickets: 2,
  socialPosts: 5,
  unreadNotifications: 3,
  auditLogs: 100,
  errorLogs: 2,
};
