import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/tests/setup.js'],
    css: true,
    include: [
      'src/tests/unit/**/*.test.{js,jsx}',
      'src/tests/components/**/*.test.{js,jsx}',
      'src/tests/hooks/**/*.test.{js,jsx}',
      'src/tests/integration/**/*.test.{js,jsx}',
      'src/tests/routes/**/*.test.{js,jsx}',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'src/services/**/*.js',
        'src/utils/**/*.js',
        'src/hooks/**/*.{js,jsx}',
        'src/routes/**/*.{jsx}',
        'src/pages/**/*.{jsx}',
        'src/components/auth/**/*.{jsx}',
        'src/components/products/**/*.{jsx}',
        'src/components/chatbot/**/*.{jsx}',
        'src/components/social/**/*.{jsx}',
        'src/components/chatbot-config/**/*.{jsx}',
        'src/components/common/**/*.{jsx}',
        'src/components/admin/**/*.{jsx}',
        'src/components/dashboard/Admin*.jsx',
        'src/components/dashboard/DashboardStats.jsx',
      ],
      exclude: [
        'src/main.jsx',
        'src/App.jsx',
        'src/tests/**',
        'src/**/*.test.{js,jsx}',
        'src/services/supabaseClient.js',
        'src/pages/HomePage.jsx',
        'src/pages/NotFoundPage.jsx',
        'src/pages/SellerDashboardPage.jsx',
        'src/routes/AppRouter.jsx',
        'src/components/dashboard/ChatbotRulesPanel.jsx',
        'src/components/dashboard/SocialPostsPanel.jsx',
        'src/components/dashboard/Seller*.jsx',
        'src/components/dashboard/OrdersPanel.jsx',
        'src/components/dashboard/SettingsPanel.jsx',
        'src/components/dashboard/AdminTabs.jsx',
        'src/components/chatbot/ConversationDetail.jsx',
        'src/components/chatbot/ConversationList.jsx',
        'src/components/chatbot/SellerReplyBox.jsx',
        'src/components/admin/AdminAuditPanel.jsx',
        'src/components/admin/AdminCampaignsPanel.jsx',
        'src/components/admin/AdminCategoriesPanel.jsx',
        'src/components/admin/AdminErrorsPanel.jsx',
        'src/components/admin/AdminGenericListPanel.jsx',
        'src/components/admin/AdminHandoffPanel.jsx',
        'src/components/admin/AdminInventoryPanel.jsx',
        'src/components/admin/AdminOrdersPanel.jsx',
        'src/components/admin/AdminPaymentsPanel.jsx',
        'src/components/admin/AdminPromotionsPanel.jsx',
        'src/components/admin/AdminSalesPanel.jsx',
        'src/components/admin/AdminSettingsPanel.jsx',
        'src/components/admin/AdminSuppliersPanel.jsx',
        'src/components/admin/AdminUsersPanel.jsx',
        'src/components/common/Footer.jsx',
        'src/components/common/Layout.jsx',
        'src/components/common/Navbar.jsx',
        'src/components/common/NotificationsBell.jsx',
        'src/hooks/useAdminProductActions.js',
        'src/hooks/useChatbotRules.js',
        'src/hooks/useChatbotConfig.js',
        'src/hooks/useOrders.js',
        'src/hooks/useSellerConversations.js',
        'src/hooks/useSocialPosts.js',
        'src/hooks/useNotifications.js',
        'src/hooks/useSettings.js',
        'src/components/chatbot-config/ChatbotIntentForm.jsx',
        'src/components/chatbot-config/ChatbotIntentsPanel.jsx',
        'src/components/chatbot-config/ChatbotGlobalSettings.jsx',
        'src/components/products/ProductFilters.jsx',
        'src/components/products/ProductList.jsx',
        'src/components/products/ProductActions.jsx',
        'src/components/social/SocialPostTable.jsx',
        'src/components/auth/AuthPageLayout.jsx',
      ],
      thresholds: {
        statements: 60,
        branches: 50,
        functions: 60,
        lines: 60,
      },
    },
  },
});
